- .github/workflows/codeql-analysis.yml
- setup.py
* fix backup tool 
* Create code analysis
> fix backup tool

- docker/melodic/Dockerfile
- docker/noetic/Dockerfile
[^note]:
Put an `x` into the [ ] to show you have filled the information.
The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
You can override it by creating .github/pull_request_template.md  in your own repository
> switch to github public registry

- backend/endpoints/api/v1/restapi.py
- backend/endpoints/auth.py
- docker/melodic/Dockerfile
- docker/noetic/Dockerfile
- setup.py
Feat: containers build from public repo
> Feat: containers build from public repo

- backend/endpoints/api/v1/restapi.py
- backend/endpoints/api/v1/v1.py
- [FP-1881 - Create Endpoint to get Classes definitions for autocomplete in Python Callbacks](https://movai.atlassian.net/browse/FP-1881)
- [FP-1882 - Use endpoint to populate autocomplete in python Language Server](https://movai.atlassian.net/browse/FP-1882)
> add get callback builtins api

- .bumpversion.cfg
- .github/workflows/DeployOnGitRelease.yml
- .github/workflows/DeployOnMergeMain.yml
- .github/workflows/TestOnPR.yml
- backend/endpoints/api/v1/restapi.py
- backend/endpoints/api/v1/v1.py
- docker/melodic/Dockerfile
- docker/noetic/Dockerfile
- setup.py
> Fix : noetic pipeline issue

- .bumpversion.cfg
- backend/tools/deploy_app.py
- backend/tools/gen_report.py
- backend/tools/new_user.py
- build-requirements.txt
- requirements.txt
- setup.py
This branch contains the necessary changes for the updated split.
jira:
https://movai.atlassian.net/browse/BP-833?atlOrigin=eyJpIjoiNTg3YjBkNGJkNDA2NDZhYmFlNzI0OGI1NjEwYmMzNDYiLCJwIjoiaiJ9
'- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue'
[^note]:
Put an `x` into the [ ] to show you have filled the information.
The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
You can override it by creating .github/pull_request_template.md  in your own repository
> Feature bp 833 prepare for deployment on backend

- README.md
- setup.py
jira:
https://movai.atlassian.net/browse/BP-869?atlOrigin=eyJpIjoiMGVlMGU2NzBmMTk0NDZjYmE0YjNmYjMwM2U2ZjA4ZWIiLCJwIjoiaiJ9
> update setup.py to rely on 2.4.0.x

- backend/__main__.py
- docker/files/packages.apt
[863](https://movai.atlassian.net/browse/BP-863?atlOrigin=eyJpIjoiYmVlM2UwNDcwMjEyNGRhZDgxNmRlY2YyMDkxOWFmZWQiLCJwIjoiaiJ9) - adding logs handler
> Feature bp 863 implement logs handler

- backend/__main__.py
- backend/endpoints/api/v1/restapi.py
[BP-865](https://movai.atlassian.net/browse/BP-865?atlOrigin=eyJpIjoiZjllMTcwZjU4M2U2NDhmZjliZjkzYjMwZDlkZGM1MTIiLCJwIjoiaiJ9)
this PR implemets the LogsQuesry handler and make some major changes to message-server solution
[BP-865]: https://movai.atlassian.net/browse/BP-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature bp 865 add support for logs querying

- backend/endpoints/api/v1/restapi.py
update to the correct import from the enterprise edition
> added fixes for the enterprise after the fix

- backend/endpoints/api/v1/restapi.py
hot fix to fix the ci cd on the sonar cloud
> fixing the critical issue from the sonar cloud

- .flake8
small update to flake8
and to update with a new container that will include the latest data-access-layer with the latest fixes
> dummy commit with small update to flake8

- backend/endpoints/api/v1/restapi.py
[BP-649](https://movai.atlassian.net/browse/BP-649?atlOrigin=eyJpIjoiODYzMzJkYzk2Yzc0NGM5MjhjNzYzMjJiMGVkODYxN2IiLCJwIjoiaiJ9)
[BP-649]: https://movai.atlassian.net/browse/BP-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> use ZMQ for metrics create and search

- backend/endpoints/api/v2/notifications.py
> remove commented logic

- backend/endpoints/api/v1/restapi.py
[BP-906](https://movai.atlassian.net/browse/BP-906) - Tag ui is not workin
[BP-929](https://movai.atlassian.net/browse/BP-929) - Robot card showing all logs including backend
[BP-906]: https://movai.atlassian.net/browse/BP-906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-929]: https://movai.atlassian.net/browse/BP-929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tag UI is not working and robot card showing extra logs

- backend/endpoints/api/v1/restapi.py
- backend/endpoints/api/v1/robot_reovery.py
Finally tested,
But depends on this: https://github.com/MOV-AI/data-access-layer/pull/119
> fix robot recovery

- backend/endpoints/api/v1/restapi.py
- pyproject.toml
a fix that pushed to classes By @Mograbi 
and added here also
> fix for deleting ports with nodes

- backend/endpoints/api/v1/restapi.py
- backend/endpoints/api/v1/robot_reovery.py
[BP-603](https://movai.atlassian.net/browse/BP-603) - when exposed port is deleted it doesn't get removed from Redis
frontend trigger robot recovery 
[BP-603]: https://movai.atlassian.net/browse/BP-603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> backend 2.4.1.9 - fixes for robot recovery and deletion of exposed ports

- .bumpversion.cfg
- setup.py
> CICD : Sync main and dev

- .bumpversion.cfg
- .github/workflows/DeployOnMergeMain.yml
- .github/workflows/TestOnPR.yml
- setup.py
> CICD : fix pipeline triggers

- README.md
dummy commit to rebuild image because movai-core-shared and data-access-layer got updated
> version 2.4.1.13

- .github/workflows/DeployOnGitRelease.yml
- .github/workflows/DeployOnMergeMain.yml
- README.md
CICD : fix branch protection and commit password
> CICD : fix branch protection and commit password

- README.md
- setup.py
> updated gd-node version

- README.md
- setup.py
- [BP-958](https://movai.atlassian.net/browse/BP-958): Task manager - err in generating tasks 
[BP-958]: https://movai.atlassian.net/browse/BP-958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-958 updated dal version

- backend/endpoints/api/v1/restapi.py
- setup.py
[BP-989](https://movai.atlassian.net/browse/BP-989) - separate metrics to different measurements in influxdb
DAL:
[BP-771](https://movai.atlassian.net/browse/BP-771): Fleet var mentioned on a node parameter is not correctly parsed.
[BP-958](https://movai.atlassian.net/browse/BP-958): Task manager - err in generating tasks
[BP-1020](https://movai.atlassian.net/browse/BP-1020): Installation of packages inside flow-initiator hang if it was not started as a robot
shared:
[BP-995](https://movai.atlassian.net/browse/BP-995): Alerts silently breaking in 2.4
[BP-1019](https://movai.atlassian.net/browse/BP-1019): New spam log
[BP-1023](https://movai.atlassian.net/browse/BP-1023): display message server messages in readable format
gd-node:
[BP-996](https://movai.atlassian.net/browse/BP-996): Not …
> version 2.4.1.21

- backend/endpoints/api/v1/restapi.py
- setup.py
* send name parameter as the measurement argument to get_metrics function
* updating get_metrics function
* adding await for get_metrics response
* remove await
* update setup.py
* updat docstring
> Backend v2.4.1.22

- backend/__init__.py
- setup.py
called create_default_roles instead of dal
> version 2.4.1.23

- setup.py
updating the dal with fix for:
Should fix:
- [BP-1024](https://movai.atlassian.net/browse/BP-1024): Backend, object is not JSON serializable followed by Segmentation fault
-  [BP-1028](https://movai.atlassian.net/browse/BP-1028): Backend restarting and UI test failling
-  [BP-1032](https://movai.atlassian.net/browse/BP-1032): User with admin role can not login to the system
[BP-1032]: https://movai.atlassian.net/browse/BP-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1024]: https://movai.atlassian.net/browse/BP-1024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1028]: https://movai.atlassian.net/browse/BP-1028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …
> updating dal to fix BP-1032

- .bumpversion.cfg
- backend/__init__.py
- backend/tools/new_user.py
- setup.py
[BP-840](https://movai.atlassian.net/browse/BP-840) - use entrypoints for tools
restore new_user because it cause bug in movai-service
[BP-840]: https://movai.atlassian.net/browse/BP-840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> version 2.4.1.26

- backend/__init__.py
- backend/tools/new_user.py
[BP-1032](https://movai.atlassian.net/browse/BP-1032): User with admin role can not login to the system
[BP-1032]: https://movai.atlassian.net/browse/BP-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> version 2.4.1.27

- backend/endpoints/static.py
- [BP-1033](https://movai.atlassian.net/browse/BP-1033): Get on maps endpoint for inexisting map returns 200
[BP-1033]: https://movai.atlassian.net/browse/BP-1033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fixed not found problem

- README.md
- setup.py
- [BP-1043](https://movai.atlassian.net/browse/BP-1043): Flow stuck during transition
[BP-1043]: https://movai.atlassian.net/browse/BP-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> pump dal version

- .pylintrc
- backend/core/log_streamer/__init__.py
- backend/core/log_streamer/log_client.py
- backend/core/log_streamer/log_filter.py
- backend/core/log_streamer/logs_streamer.py
- backend/endpoints/api/v1/restapi.py
- backend/endpoints/ws.py
- backend/helpers/rest_helpers.py
- setup.py
[BP-984](https://movai.atlassian.net/browse/BP-984) - stream logs from message-server to backend
[BP-985](https://movai.atlassian.net/browse/BP-985) - stream logs from backend to frontend
> Version 2.4.1.32

- setup.py
Fixes for:
- [BP-1053](https://movai.atlassian.net/browse/BP-1053): performance enhancement for Configuration
- [BP-1041](https://movai.atlassian.net/browse/BP-1041): Callback started to give I/O operation error on ee-platform 2.4.0-58
- [BP-1051](https://movai.atlassian.net/browse/BP-1051): Specify log name
[BP-1053]: https://movai.atlassian.net/browse/BP-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1041]: https://movai.atlassian.net/browse/BP-1041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1051]: https://movai.atlassian.net/browse/BP-1051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> adding the latest fixes

- backend/__init__.py
- backend/core/log_streamer/log_client.py
- backend/core/log_streamer/logs_streamer.py
- backend/endpoints/api/v1/restapi.py
- backend/endpoints/ws.py
- backend/helpers/rest_helpers.py
- setup.py
[BP-1045](https://movai.atlassian.net/browse/BP-1045) - migrate message server dispatchers to zmqserver
[BP-1046](https://movai.atlassian.net/browse/BP-1046) - ZMQ error after running the flow for a while
[BP-1049](https://movai.atlassian.net/browse/BP-1049) - Metrics are intermittendly breaking
[BP-1057](https://movai.atlassian.net/browse/BP-1057) - Logs API response structure was changed
[BP-1045]: https://movai.atlassian.net/browse/BP-1045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1046]: https://movai.atlassian.net/browse/BP-1046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1049]: https://movai.atlassian.net/browse/BP-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
> BP-1045 - migrate message server dispatchers to zmqserver

- backend/__init__.py
- backend/core/log_streamer/log_client.py
- backend/core/log_streamer/logs_streamer.py
- backend/endpoints/api/v1/restapi.py
- backend/endpoints/ws.py
- backend/helpers/rest_helpers.py
- setup.py
[BP-1045](https://movai.atlassian.net/browse/BP-1045) - migrate message server dispatchers to zmqserver
[BP-1046](https://movai.atlassian.net/browse/BP-1046) - ZMQ error after running the flow for a while
[BP-1049](https://movai.atlassian.net/browse/BP-1049) - Metrics are intermittendly breaking
[BP-1057](https://movai.atlassian.net/browse/BP-1057) - Logs API response structure was changed
[BP-1045]: https://movai.atlassian.net/browse/BP-1045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1046]: https://movai.atlassian.net/browse/BP-1046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1049]: https://movai.atlassian.net/browse/BP-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
> Version 2.4.1.34

- setup.py
> Version fix shared

- backend/__init__.py
- backend/endpoints/auth.py
- setup.py
[BP-1079](https://movai.atlassian.net/browse/BP-1079) - backend does not start
[BP-1079]: https://movai.atlassian.net/browse/BP-1079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1079 - backend does not start

- backend/__init__.py
- backend/endpoints/auth.py
- setup.py
[BP-1074](https://movai.atlassian.net/browse/BP-1074) - update TimeSeriesDBHandler to support bulk inserts
[BP-1071](https://movai.atlassian.net/browse/BP-1071) - upgrade stress handler to have insert and query tests as well
[BP-1074]: https://movai.atlassian.net/browse/BP-1074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1071]: https://movai.atlassian.net/browse/BP-1071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update movai-core-shared to 2.4.1.24

- setup.py
* Bump requests: 2.22.0 -> 2.28.2
* Bump movai-core-shared: 2.4.1.26 -> 2.4.1.30
* Bump gd-node: 2.4.1.17 -> 2.4.1.19
> Version: 2.4.1.42 Bumping Dependencies

- backend/endpoints/auth.py
[BP-1092](https://movai.atlassian.net/browse/BP-1092) - remove expired tokens not working
[BP-1092]: https://movai.atlassian.net/browse/BP-1092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1092 - remove expired tokens not working

- backend/endpoints/auth.py
- setup.py
[BP-1092](https://movai.atlassian.net/browse/BP-1092) - remove expired tokens not working
[BP-1092]: https://movai.atlassian.net/browse/BP-1092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> version 2.4.1.43

- backend/endpoints/api/v1/restapi.py
- [BP-1037](https://movai.atlassian.net/browse/BP-1037) / [BP-1038](https://movai.atlassian.net/browse/BP-1038): Error when saving Node, when a port has changed from subscriber to publisher
- before fully deleting a port we need to check if that port really exist/not in the new_dict from the POST request.
[BP-1037]: https://movai.atlassian.net/browse/BP-1037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1038]: https://movai.atlassian.net/browse/BP-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version 2.4.1.44

- README.md
- backend/endpoints/api/v1/restapi.py
- setup.py
> Version 2.4.1.45

- backend/endpoints/api/v2/alerts.py
- setup.py
- bump movai-core-shared
- [BP-1104](https://movai.atlassian.net/browse/BP-1104): Alerts config and emails api's don't save the data on redis, in #165 
[BP-1104]: https://movai.atlassian.net/browse/BP-1104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version 2.4.1.46

- .bumpversion.cfg
- .github/workflows/TestOnPR.yml
Going to merge so you can work smoothly on sunday.
> have bump version raise based on 4 digits only

- setup.py
[BP-255](https://movai.atlassian.net/browse/BP-255) - integrating the spawner
[BP-255]: https://movai.atlassian.net/browse/BP-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version 2.5.0.4

- setup.py
data-access-layer: 2.5.0.4 ->  2.5.0.5
> [hotfix] Version 2.5.0.5

- backend/endpoints/api/v1/__init__.py
- backend/endpoints/api/v1/frontend/__init__.py
- backend/endpoints/api/v1/frontend/fleetdashboard/__init__.py
- backend/endpoints/api/v1/frontend/fleetdashboard/api.py
- backend/endpoints/api/v1/frontend/fleetdashboard/statistics.py
- backend/endpoints/api/v1/frontend/fleetdashboard/tasks.py
- backend/endpoints/api/v1/frontend/ide/__init__.py
- backend/endpoints/api/v1/frontend/ide/callbackeditor.py
- backend/endpoints/api/v1/frontend/ide/datavalidation.py
- backend/endpoints/api/v1/frontend/ide/flowtopbar.py
- backend/endpoints/api/v1/frontend/ide/getportsdata.py
- backend/endpoints/api/v1/frontend/ide/startsystemwidget.py
- backend/endpoints/api/v1/frontend/ide/viewer.py
- backend/endpoints/api/v1/frontend/taskmanager/__init__.py
- backend/endpoints/api/v1/frontend/taskmanager/api.py
- backend/endpoints/api/v1/frontend/taskmanager/generate_sde.py
- backend/endpoints/api/v1/restapi.py
- backend/endpoints/api/v1/v1.py
- backend/endpoints/api/v2/__init__.py
- backend/endpoints/api/v2/base.py
- setup.py
[BP-872](https://movai.atlassian.net/browse/BP-872) - convert frontend callback to rest api
[BP-872]: https://movai.atlassian.net/browse/BP-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version 2.5.0.7

- backend/endpoints/api/v1/frontend/__init__.py
- backend/endpoints/api/v1/frontend/fleetdashboard/__init__.py
- backend/endpoints/api/v1/frontend/fleetdashboard/api.py
- backend/endpoints/api/v1/frontend/fleetdashboard/statistics.py
- backend/endpoints/api/v1/frontend/fleetdashboard/tasks.py
- backend/endpoints/api/v1/frontend/ide/__init__.py
- backend/endpoints/api/v1/frontend/ide/viewer.py
- backend/endpoints/api/v1/frontend/taskmanager/__init__.py
- backend/endpoints/api/v1/frontend/taskmanager/api.py
- backend/endpoints/api/v1/frontend/taskmanager/generate_sde.py
- backend/endpoints/api/v1/restapi.py
- setup.py
[BP-872](https://movai.atlassian.net/browse/BP-872) - convert frontend callback to rest api
fix a bug preventing the backend from loading when movai-core-entperise is not installed
[BP-872]: https://movai.atlassian.net/browse/BP-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version 2.5.0.8

- backend/core/permission.py
- backend/endpoints/api/v1/frontend/fleetmanager/statistics.py
- backend/endpoints/api/v1/frontend/ide/callbackeditor.py
- backend/endpoints/api/v1/frontend/ide/datavalidation.py
- backend/endpoints/api/v1/frontend/ide/getportsdata.py
- backend/endpoints/api/v1/frontend/ide/viewer.py
- backend/endpoints/api/v1/restapi.py
- backend/endpoints/api/v2/alerts.py
- backend/endpoints/api/v2/base.py
- backend/endpoints/api/v2/role.py
- backend/endpoints/static.py
- backend/tools/deploy_app.py
- backend/tools/upload_ui.py
- setup.py
pydantic baseline for 2.4.1:
[BP-1001](https://movai.atlassian.net/browse/BP-1001) - create Callback pydantic class
[BP-1002](https://movai.atlassian.net/browse/BP-1002) - create Configuration pydantic class
[BP-999](https://movai.atlassian.net/browse/BP-999) - create Flow pydantic class
[BP-1110](https://movai.atlassian.net/browse/BP-1110) - create Message pydantic class
[BP-1000](https://movai.atlassian.net/browse/BP-1000) - create Node pydantic class
[BP-1009](https://movai.atlassian.net/browse/BP-1009) - create Ports pydantic class
[BP-1114](https://movai.atlassian.net/browse/BP-1114) - create System pydantic class
[BP-1001]: https://movai.atlassian.net/browse/BP-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1002]: …
> Version 2.5.0.11

- .bumpversion.cfg
- backend/endpoints/api/v1/frontend/ide/flowtopbar.py
- backend/endpoints/api/v1/restapi.py
- backend/tools/deploy_app.py
- backend/tools/upload_ui.py
- setup.py
[BP-1156](https://movai.atlassian.net/browse/BP-1156) - movai-cli frontend command is failing
[BP-1156]: https://movai.atlassian.net/browse/BP-1156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BP-1156 - movai-cli frontend command is failing 

- backend/endpoints/api/v1/frontend/ide/viewer.py
- backend/endpoints/api/v1/restapi.py
- backend/endpoints/api/v2/alerts.py
- backend/endpoints/api/v2/db.py
- setup.py
[BP-1161](https://movai.atlassian.net/browse/BP-1161) - fix new and init on MovaiBaseModel
[BP-1161]: https://movai.atlassian.net/browse/BP-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version 2.5.0.14

- .bumpversion.cfg
- backend/endpoints/api/v2/db.py
- setup.py
BP-1161 - fix new and init on MovaiBaseModel (#186)
> Version 2.5.0.15

- .pre-commit-config.yaml
- .pylintrc
- setup.py
ZMQ socket not working in hostmode=true
replace ZMQ communication with spawner from TCP to a unix file socket shared between containers
> DP-1384: prepare update of core-shared and dal with new spawner_bind_address

- .bumpversion.cfg
- backend/endpoints/api/v1/frontend/ide/viewer.py
- backend/endpoints/api/v1/restapi.py
- setup.py
Fix to the issue reported in https://movai.atlassian.net/browse/BP-1162
Also fixes some syntax problems from the callback code copied from the frontend repo.
---
[^note]:
Put an `x` into the [ ] to show you have filled the information.
The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
You can override it by creating .github/pull_request_template.md  in your own repository
> BP-1162: Fail to update graphic scene

- setup.py
- integrating https://github.com/MOV-AI/movai-core-shared/releases/tag/2.5.0.13
- remove requests dependency since it is mentinned in `movai-core-shared`
> Fix DP-1504: zmq communication error on backend

- setup.py
Sync due to https://github.com/MOV-AI/flow-initiator/pull/141
> Bump dal, sync with flow-initiator

- .pre-commit-config.yaml
- backend/core/log_streaming/log_client.py
- backend/core/log_streaming/log_streamer.py
- backend/docs/git-v2-2.4.yaml
- backend/docs/notifications-v2-2.4.yaml
- backend/endpoints/api/v1/__init__.py
- backend/endpoints/api/v1/frontend/__init__.py
- backend/endpoints/api/v1/frontend/fleetmanager/__init__.py
- backend/endpoints/api/v1/frontend/taskmanager/__init__.py
- backend/endpoints/api/v1/frontend/taskmanager/api.py
- backend/endpoints/api/v1/frontend/taskmanager/generate_sde.py
- backend/endpoints/api/v1/restapi.py
- backend/endpoints/api/v1/robot_reovery.py
- backend/endpoints/api/v1/v1.py
- backend/endpoints/api/v2/__init__.py
- backend/endpoints/api/v2/alerts.py
- backend/endpoints/api/v2/base.py
- backend/endpoints/auth.py
- backend/endpoints/ws.py
- backend/helpers/rest_helpers.py
- docs/api/v2/email_alerts.yaml
- setup.py
DP-1504 : update movai-core-shared
> DP-1504 : update movai-core-shared

- backend/endpoints/api/v2/notifications.py
DP-1504: Update notifications.py with renaming of respose_required
---
> DP-1504: Update notifications.py with renaming of respose_required

- backend/endpoints/ws.py
- setup.py
> bring fixes from 2.3

- .github/workflows/DeployOnGitRelease.yml
- .github/workflows/DeployOnMergeMain.yml
- .github/workflows/TestOnPR.yml
- setup.py
- [BP-1237](https://movai.atlassian.net/browse/BP-1237): Small code fix
- [BP-1206](https://movai.atlassian.net/browse/BP-1206): Fix incorrect port remaps
[BP-1237]: https://movai.atlassian.net/browse/BP-1237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1206]: https://movai.atlassian.net/browse/BP-1206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update data-access-layer to 2.5.0.25

- setup.py
Revert dal's CallbackSubscription.
>  Revert CallbackSubscription
